### ISSUE TITLE
Language issue in Virtual Event Code of Conduct

### ISSUE THREAD

**Issue by abdulrehmanaftab** [microsoft/virtual-events#11]
Please check below link. This all should be in English language rather than a mixture of English and some other language.

[https://github.com/microsoft/virtual-events/blob/main/virtual-event-code-of-conduct.md](https://github.com/microsoft/virtual-events/blob/main/virtual-event-code-of-conduct.md)

**Comment by csharpfritz** [comment]
Yes, this looks like it was intended to be a translation and wasn't saved well

+ @jennymevents

**Comment by jennymevents** [comment]
Thank you for letting me know! Fixed ASAP. Thank you!
